### PR TITLE
Homework1: Anton Kochnevski 

### PR DESCRIPTION
**Pull request by Antonkoch999**

### CODE REVIEW

**Review by belovmd — COMMENTED** [review]
Thank you for your work. 
Please address next paragraphs from review notes [Review Notes](https://github.com/belovmd/it-academy-summer/blob/master/Homework%20review/Homework2.md):
- failed checks - bad naming
- redundant file in code (123.txt)

**Comment by Antonkoch999** [comment]
delete a file 123.txt

**Comment by Antonkoch999** [comment]
Ready to check!

**Comment by belovmd** [comment]
1

**Pull request closed without merging**
